---
# https://hub.docker.com/_/vault?tab=tags

version: "3"
services:
  vault:
    container_name: vault
    image: vault:1.5.4
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID:
    cap_add:
      - IPC_LOCK
